### ISSUE TITLE
Constrain all image and text element sizes to fit within a 300px with iframe without horizontal scrollbars

### ISSUE THREAD

**Issue by smcnally** [smcnally/office_quiz#25]
I'm working from the branch [issue-23_add_swipe](https://github.com/smcnally/office_quiz/tree/issue-23_add_swipe)

Please create branch `farcreative` from `issue-23_add_swipe` if you make changes. 

In [index.css](https://github.com/smcnally/office_quiz/blob/issue-23_add_swipe/src/index.css#L529-L557), constraints are in place to ensure all elements are 299x599 or less. 

I see no element in Dev Tools larger than 299px in width. 
But I still get horizontal scrollbars. 

I need the game being pulled into the iframe src to fit in < 300px and get rid of the horizontal scroll bars. 

Would you please have a look and let me know if you see what's causing this horizontal scroll. 

[Plain_iFrame.html](http://meanbusiness.com/gamepath/qp/lucent/Plain_iFrame.html) pulls 1[80918-Dosage_Calculator](http://meanbusiness.com/gamepath/qp/lucent/180918-Dosage_Calculator/) into an iframe. 

![image](https://user-images.githubusercontent.com/850878/45725678-c45d9a00-bb70-11e8-83a4-ceaa2e110590.png)

![image](https://user-images.githubusercontent.com/850878/45725685-caec1180-bb70-11e8-95f0-18d921495aa6.png)

**Comment by FARCreative** [comment]
Your iframe and content inside had almost the same width. But content height is more then 600px so iframe had his own scrollbar and the space for its content was reduced by this scrollbar width. We have set some quiz elements width to 100% instead of values in px or just removed hardcoded width. Also we have removed quiz height so that scrolling is driven by iframe. I think it's more flexible than reduce quiz size by scrollbars width (scrollbars may have different width in browsers).

I have created 'farcreative' branch with our updates of index.css. Please verify if it works for you.

**Comment by smcnally** [comment]
Many thanks. Checking out your updates and will reply. 

In general, vertical scrolling is acceptable. We can address this with changing the game content, as you note, rather than css / code. Horizontal scrolling is crappy UX so I'd like to  prevent that from occurring with css / js code as needed.

**Comment by smcnally** [comment]
Looks good. I'm closing this ticket. I'll reach out with any questions I have during review and merging your branch. 

Thank you for the quick turn-around on this.
